#!/bin/bash

set -e

echo '--> Installing dependencies'
sudo apt-get update > /dev/null
sudo apt-get install -y --force-yes fuse-zip > /dev/null

echo '--> Mounting zipfile'
mkdir zipmount
fuse-zip test.zip zipmount

echo '--> Testing'
sleep 1
mount
sudo test -f zipmount/hello || echo 'File not found in mount'; exit 1
